services:
  frontend-config:
    image: busybox:latest
    volumes:
      - ./src/config:/app/src/config
    entrypoint: >
      sh -c "echo 'const config = {
        baseUrl: \"https://dev.konzelmann.com.br\"
      };
      export default config;' > /app/src/config/apiConfig.js"
    environment:
      - BASE_URL=https://dev.konzelmann.com.br
    restart: "no"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lojinha-frontend
    ports:
      - "8080:80"
    depends_on:
      - frontend-config
    volumes:
      - ./src/config:/app/src/config
    restart: "unless-stopped"
