services:
  app:
    container_name: frontend
    image: adenilsonkon/devopslabs01-frontend:latest
    build : 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped