name: Publish docker image on DockerHub

on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    name: docker build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            adenilsonkon/devopslabs-frontend
          tags: |
            type=sha
            
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ steps.meta.outputs.tags }}
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push the Docker image tag hash
        run: docker push ${{ steps.meta.outputs.tags }}
        
      - name: Push the Docker image tag latest
        run: docker tag ${{ steps.meta.outputs.tags }} adenilsonkon/devopslabs-frontend:latest && docker push adenilsonkon/devopslabs-frontend:latest
